### ISSUE TITLE
invalid master username for the RDS

### ISSUE THREAD

**Issue by maestrofx** [stackwire-io/rancher-cluster#1]
Hi there,
I've trying out this repo and find this error:

```
Error applying plan:

1 error(s) occurred:

* aws_db_instance.rancher: 1 error(s) occurred:

* aws_db_instance.rancher: Error creating DB Instance: InvalidParameterValue: Invalid master user name
	status code: 400, request id: xxx-xxx-xxx-xxx

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

It's stuck on the invalid master username for the RDS.

Any help, please!
Thank you.

**Comment by barryw** [comment]
Hi!

What did you set the `master_username` parameter to in your `tfvars` file? That should be a valid MySQL username. I generally use `rancher`.

As an example, here's my `tfvars`

```
access_key="***"
secret_key="***"
aws_region="us-west-2"
master_hostname="rancher"
zone_id="Z1IXMYNDBTV4UF"
acm_ssl_cert_arn="arn:aws:acm:us-west-2:155929161910:certificate/48d57824-21e8-4af2-8a8e-9d89dfca8172"
key_name="stackwire-us-west-2"
master_username="rancher"
environment="walkerdba"
```

**Comment by maestrofx** [comment]
Hi @barryw ,

the error's caused by this param using dash (-):
`master_username="rancher-admin"`

When I create it with 'rancher' or 'rancheradmin', it returns success.

Thank you.

**Comment by atrakic** [comment]
Just to confirm I experienced same while using ${random_pet.master_username.id} and failed. So obviously it should be value without dash (but documentation doesn't say anything about it).

**Comment by JoshCoady** [comment]
The [docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_CreateDBInstance.html) list these requirements:

> - It can contain 1–16 alphanumeric characters and underscores.
> - Its first character must be a letter.
> - It can't be a word reserved by the database engine.

So only letters, numbers, and underscores.
